import { useEffect, useState } from "react";
import { api } from "../api";
import { useStore } from "../store";
import { TextGeneratorModal } from "../components/TextGeneratorModal";

export function BrainstormSession() {
  const {
    currentProject, rootDir, bank, stage, stageMessage, overallPct,
    domains, liveIdeas, applyEvent, reset, setView, setCurated,
    setReport, setProject, runError, setRunError, brainstormId, iter,
  } = useStore();

  const [running, setRunning] = useState(false);
  const [showTextGen, setShowTextGen] = useState(false);
  const [showTexts, setShowTexts] = useState(false);
  const noTexts = !bank?.reference_texts?.length;
  const textCount = bank?.reference_texts?.length ?? 0;
  const isFirstRun = !brainstormId;

  useEffect(() => {
    const off = api.brainstorm.onEvent((e) => applyEvent(e));
    return () => { off(); };
  }, [applyEvent]);

  async function start() {
    if (!currentProject) return;
    reset();
    setRunError(undefined);
    setRunning(true);
    try {
      const result = (await api.brainstorm.run({ rootDir, name: currentProject })) as any;
      if (result?.cancelled) return;
      if (result?.curated) setCurated(result.curated);
      if (result?.report) setReport(result.report);
      setView("curation");
    } catch (err) {
      setRunError(err instanceof Error ? err.message : String(err));
    } finally {
      setRunning(false);
    }
  }

  async function cancel() {
    await api.brainstorm.cancel();
    setRunning(false);
  }

  async function handleTextsSaved() {
    setShowTextGen(false);
    if (currentProject) {
      const loaded = (await api.project.load({ rootDir, name: currentProject })) as any;
      setProject(currentProject, rootDir, loaded.brief, loaded.bank, loaded.config);
    }
  }

  async function deleteText(textId: string) {
    if (!currentProject) return;
    await api.texts.delete({ rootDir, name: currentProject, textId });
    const loaded = (await api.project.load({ rootDir, name: currentProject })) as any;
    setProject(currentProject, rootDir, loaded.brief, loaded.bank, loaded.config);
  }

  return (
    <div className="mx-auto max-w-6xl p-6">
      {showTextGen && currentProject && (
        <TextGeneratorModal
          projectName={currentProject}
          rootDir={rootDir}
          onSaved={handleTextsSaved}
          onClose={() => setShowTextGen(false)}
        />
      )}

      {/* Header row */}
      <div className="mb-5 flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Brainstorm</h1>
          <p className="mt-0.5 text-xs text-slate-500">
            Each run generates distant knowledge probes, collides them with your reference texts,
            and surfaces the best ideas.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button className="btn-ghost text-sm" onClick={() => setShowTextGen(true)}>
            ✨ {noTexts ? "Generate reference texts" : "Add texts"}
          </button>
          {running ? (
            <button className="btn bg-rose-600 hover:bg-rose-500" onClick={cancel}>
              ✕ Cancel run
            </button>
          ) : (
            <button className="btn" onClick={start} disabled={!currentProject || noTexts}>
              {isFirstRun ? "Start brainstorm" : "Run again"}
            </button>
          )}
        </div>
      </div>

      {/* No texts warning */}
      {noTexts && (
        <div className="mb-4 flex items-center justify-between rounded-lg border border-amber-700/50 bg-amber-900/20 p-3 text-sm text-amber-300">
          <span>No reference texts yet — ideas are generated by colliding texts with knowledge probes. Add at least one.</span>
          <button className="btn ml-4 shrink-0 bg-amber-600 hover:bg-amber-500" onClick={() => setShowTextGen(true)}>
            Generate with AI
          </button>
        </div>
      )}

      {/* Error state */}
      {runError && (
        <div className="mb-4 rounded-lg border border-rose-700/50 bg-rose-900/20 p-3">
          <div className="text-sm font-medium text-rose-300">Run failed</div>
          <div className="mt-1 text-xs text-rose-400">{runError}</div>
          <div className="mt-2 text-xs text-slate-400">
            Any completed stages were saved to disk — you can review the Report or retry.
          </div>
          <button className="btn mt-3 text-xs" onClick={start} disabled={noTexts}>Retry</button>
        </div>
      )}

      {/* Reference texts panel */}
      {textCount > 0 && (
        <div className="mb-4">
          <button
            className="flex items-center gap-1 text-xs text-slate-500 hover:text-slate-300"
            onClick={() => setShowTexts(!showTexts)}
          >
            <span>{showTexts ? "▾" : "▸"}</span>
            {textCount} reference text{textCount !== 1 ? "s" : ""} loaded
          </button>
          {showTexts && (
            <div className="mt-2 space-y-2">
              {bank!.reference_texts.map((t) => (
                <div key={t.id} className="card flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-mono text-slate-600">{t.id}</span>
                      <span className="text-sm font-medium">{t.label}</span>
                    </div>
                    <div className="mt-1 line-clamp-2 text-xs text-slate-500">{t.content.slice(0, 200)}…</div>
                  </div>
                  <button
                    className="shrink-0 text-xs text-slate-600 hover:text-rose-400"
                    onClick={() => deleteText(t.id)}
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Pipeline columns */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {/* Knowledge probes */}
        <section>
          <div className="mb-2 flex items-baseline gap-2">
            <h2 className="text-sm font-semibold text-slate-300">Knowledge probes</h2>
            <span className="text-xs text-slate-600">{domains.length} found</span>
            <span className="text-xs text-slate-700">— distant fields to collide with your texts</span>
          </div>
          <div className="space-y-2">
            {domains.length === 0 && !running && (
              <div className="card text-xs text-slate-600">Probes will appear here when the run starts.</div>
            )}
            {domains.map((d) => (
              <div key={d.id} className="card animate-slide-in">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-brand-500">{d.name}</span>
                  {d.origin !== "fresh" && (
                    <span className="rounded bg-slate-800 px-1.5 py-0.5 text-[10px] uppercase tracking-wide text-slate-500">
                      {d.origin}
                    </span>
                  )}
                </div>
                <div className="mt-1 text-xs text-slate-400">{d.active_principle}</div>
                <div className="mt-2 text-xs italic text-slate-600">→ {d.bridging_question}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Ideas stream */}
        <section>
          <div className="mb-2 flex items-baseline gap-2">
            <h2 className="text-sm font-semibold text-slate-300">Ideas generated</h2>
            <span className="text-xs text-slate-600">{liveIdeas.length} so far</span>
          </div>
          <div className="space-y-2">
            {liveIdeas.length === 0 && !running && (
              <div className="card text-xs text-slate-600">Ideas will stream here as each text × probe pair completes.</div>
            )}
            {liveIdeas.slice(-60).reverse().map((i) => (
              <div key={i.id} className="card animate-slide-in">
                <div className="text-[10px] uppercase tracking-wide text-slate-600">{i.text_id} × {i.domain_id}</div>
                <div className="mt-1 text-sm leading-relaxed">
                  {i.status === "failed"
                    ? <span className="text-rose-400 text-xs">Failed: {i.error}</span>
                    : i.idea}
                </div>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
